[_0]
id=0
bookId=1
connectNum=20
reward={'prop':[{'pId':860,'num':1}]}


[_1]
id=1
bookId=1
connectNum=30
reward={'prop':[{'pId':860,'num':1}]}


[_2]
id=2
bookId=1
connectNum=40
reward={'prop':[{'pId':860,'num':1}]}


[_3]
id=3
bookId=1
connectNum=50
reward={'prop':[{'pId':860,'num':1}]}


[_4]
id=4
bookId=2
connectNum=20
reward={'prop':[{'pId':860,'num':1}]}


[_5]
id=5
bookId=2
connectNum=30
reward={'prop':[{'pId':860,'num':1}]}


[_6]
id=6
bookId=2
connectNum=40
reward={'prop':[{'pId':860,'num':1}]}


[_7]
id=7
bookId=2
connectNum=50
reward={'prop':[{'pId':860,'num':1}]}


[_8]
id=8
bookId=3
connectNum=20
reward={'prop':[{'pId':860,'num':1}]}


[_9]
id=9
bookId=3
connectNum=30
reward={'prop':[{'pId':860,'num':1}]}


[_10]
id=10
bookId=3
connectNum=40
reward={'prop':[{'pId':860,'num':1}]}


[_11]
id=11
bookId=3
connectNum=50
reward={'prop':[{'pId':860,'num':1}]}


[_12]
id=12
bookId=4
connectNum=20
reward={'prop':[{'pId':860,'num':1}]}


[_13]
id=13
bookId=4
connectNum=30
reward={'prop':[{'pId':860,'num':1}]}


[_14]
id=14
bookId=4
connectNum=40
reward={'prop':[{'pId':860,'num':1}]}


[_15]
id=15
bookId=4
connectNum=50
reward={'prop':[{'pId':860,'num':1}]}


[_16]
id=16
bookId=5
connectNum=20
reward={'prop':[{'pId':860,'num':1}]}


[_17]
id=17
bookId=5
connectNum=30
reward={'prop':[{'pId':860,'num':1}]}


[_18]
id=18
bookId=5
connectNum=40
reward={'prop':[{'pId':860,'num':1}]}


[_19]
id=19
bookId=5
connectNum=50
reward={'prop':[{'pId':860,'num':1}]}


[_20]
id=20
bookId=6
connectNum=20
reward={'prop':[{'pId':860,'num':1}]}


[_21]
id=21
bookId=6
connectNum=30
reward={'prop':[{'pId':860,'num':1}]}


[_22]
id=22
bookId=6
connectNum=40
reward={'prop':[{'pId':860,'num':1}]}


[_23]
id=23
bookId=6
connectNum=50
reward={'prop':[{'pId':860,'num':1}]}


[_24]
id=24
bookId=7
connectNum=20
reward={'prop':[{'pId':860,'num':1}]}


[_25]
id=25
bookId=7
connectNum=30
reward={'prop':[{'pId':860,'num':1}]}


[_26]
id=26
bookId=7
connectNum=40
reward={'prop':[{'pId':860,'num':1}]}


[_27]
id=27
bookId=7
connectNum=50
reward={'prop':[{'pId':860,'num':1}]}


